-- Seed data for master_materials table
-- Generated from Material List.xlsx

INSERT INTO master_materials (category, name, unit) VALUES
  ('LA-CIVILWORK', 'Ultra Tech PPC', 'bags'),
  ('LA-PLUMBING WORK', 'Astral Pipe 6 Mtrs 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Pvc Wye Bend 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Bend 45 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Bend 87.5 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Pvc Coupler 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Pvc R.Bush 160x110 mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cleansing Pipe 160 mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Astral C110mm Swr Pipes 3mt', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Bend45" 110mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Coupler 110mm', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Pvc Solvent 500ml', 'nos'),
  ('LA-PLUMBING WORK', 'Astrel Cpvc Pipes (3mtrs)1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', 'Paras PTrap 110x110mm (L/H)', 'nos'),
  ('LA-PLUMBING WORK', 'Universal Clamps 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Bolts & Nuts', 'nos'),
  ('LA-PLUMBING WORK', '110mm GI Clamps', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Pipe 6 Mtrs 160mm & Astral Pipe 6 Mtrs 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Pvc Wye Bend 160mm & Astral Pvc Wye Bend 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Bend 45 160mm & Astral Bend 45 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Bend 87 5 160mm & Astral Bend 87.5 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Pvc Coupler 160mm & Astral Pvc Coupler 160mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Pvc R Bush 160x1100.mm mm & Astral PvcyeP R. Bush 160x110 mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cleansing Pipe 160 mm & Astral Cleansing Pipe 160 mm', 'nos'),
  ('LA-PLUMBING WORK', 'Antral 110mm Swr Pipes 3mt & Astral 110mm Swr Pipes 3mt', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Bend45" 110mm & Astral Bend45" 110mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Coupler 110mm & Astral Coupler 110mm', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Pvo Solvent 500ml & Prince Pvc Solvent 500ml', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cpvc Pipes (3mtrs) 1 1/4" & Astral Cpvc Pipes (3mtrs)1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', 'P Trap 110x110mm (L/H) & SWR FITINGS', 'nos'),
  ('LA-PLUMBING WORK', 'Universal Ctamps 160mm & Universal Clamps 160mm', 'nos'),
  ('LA-PLUMBING WORK', '1 10mm GI Clamps & 110mm GI Clamps', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Door Bend 110mm', 'nos'),
  ('LA-PLUMBING WORK', 'Astral CPVC Brass MTA 1 1/4 3 Astral CPVC Brass MTA 1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', 'Astral 110mm Swr Pipes 3mt', 'nos'),
  ('LA-PLUMBING WORK', 'GALAXY Teflon Tapes (White)', 'nos'),
  ('LA-PLUMBING WORK', 'lbibo CP Brass Ball Valve 1 1/4"-4704', 'pcs'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Pipe Sdr 13.5 2''''', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Elbow 2"', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cpvc Reducer Bush 2"x1 1/4', 'nos'),
  ('LA-PLUMBING WORK', 'Cpvc Reducing Bush 2x 1 1/2', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Ball Valve 2"', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Pvc Wye Bend 180mm', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Coupler 2"', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Tee 2''''', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Pipe Sdr 13.5 1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Pipe Sdr 11 1"', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Coupler 1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Срvс Tee 1"', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cрvс  Solvent 237ML', 'nos'),
  ('LA-PLUMBING WORK', 'Paras CPVC Reducer Tee 11/4"x1"', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cpvc Elbow 1"', 'nos'),
  ('LA-PLUMBING WORK', 'Astral CPVC Brass MTA  1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', '1" Cpvc End Cap', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cpvc Endcap 1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', 'Zoloto Brass Ballvalve 1"', 'nos'),
  ('LA-PLUMBING WORK', 'Zoloto Brass Ballvalve 1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Prestige Pipes 6kg -6mtrs-50mm', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Brass MTA 1"', 'nos'),
  ('LA-ELECTRICAL', '2.5 X 3C COPPER ARMD CABLE', 'MT'),
  ('LA-PLUMBING WORK', '25MM PVC PIPES NOS LMS-IVORY', 'nos'),
  ('LA-PLUMBING WORK', 'PVC LONG BENDS 25MM', 'nos'),
  ('LA-ELECTRICAL', 'PERFORATED TRAY', 'mtrs'),
  ('LA-CIVILWORK', 'ULTRATЕСН СЕМENT PPC GST 18%', 'bag'),
  ('LA-CIVILWORK', '8 MM VIZAG TMT', 'kg'),
  ('LA-CIVILWORK', '10 MM VIZAG TMT', 'kg'),
  ('LA-CIVILWORK', 'CEMENT PPC GST 18%', 'bag'),
  ('LA-PLUMBING WORK', '25MM PVC PIPES NOS HMS-GREY', 'nos'),
  ('LA-ELECTRICAL', '2.5X3C COPPER ARMD CABLE', 'mtrs'),
  ('LA-PLUMBING WORK', 'PVC TAPES NOS', 'nos'),
  ('LA-PLUMBING WORK', '25MM PVC NAILCLAMP', 'pkt'),
  ('LA-CIVILWORK', 'FOSROC BRUSHBOND RFX [5L+ 15KG]', 'nos'),
  ('LA-CIVILWORK', '315 grey', 'bag'),
  ('LA-CIVILWORK', 'M10 RMC', 'CBM'),
  ('LA-ELECTRICAL', '100W LED FLOOD LIGHT', 'nos'),
  ('LA-ELECTRICAL', '2.5X2C COPPER FLEXIBLE CABLE', 'mtrs'),
  ('LA-CIVILWORK', 'FRP MHC 600*600 OUTER 5 MT', 'nos'),
  ('LA-CIVILWORK', 'FRP MHC 450*450 2.5 MT', 'nos'),
  ('LA-CIVILWORK', 'FRP Mhc 300*300', 'nos'),
  ('LA-CIVILWORK', 'SLAB FLAMED ICONIC (Size  600X1200X10)', 'box'),
  ('LA-CIVILWORK', 'Laticrete sp100 Heмр (5kg)', 'box'),
  ('LA-CIVILWORK', 'Laticrete Resin 1.25kg', 'box'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Drain Cells 20mm Thk', 'Sq.Ft.'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Geo textile Fabrics 200 Gsm', 'sq.mtrs'),
  ('LA-CIVILWORK', 'Polished Granites-Slabs', 'Sq.Ft.'),
  ('LA-CIVILWORK', 'SLAB ELENA (Size  600X1200X10)', 'box'),
  ('LA-CIVILWORK', 'MYK LATICRETE 315 PLUS [20KG]', 'bag'),
  ('LA-PLUMBING WORK', 'Astral Cpуc Pipes Sdr 11 1"', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cpvc Coupler 1"', 'nos'),
  ('LA-PLUMBING WORK', 'Prince Cpvc Bend 45 1"', 'nos'),
  ('LA-PLUMBING WORK', 'Paras Solvent Bottle 250ML', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Non Woven Geo Textile-Sqm 2mtr x 200mtr', 'sq.mtrs'),
  ('LA-ELECTRICAL', '2.5X3C COPPER ARMD CABLE', 'mts'),
  ('LA-CIVILWORK', 'FIBER MESS 45 GSM [50 MTRS]', 'Pcs'),
  ('LA-CIVILWORK', 'FOSROC NITOBOND SBR LATEX - 20L', 'nos'),
  ('LA-CIVILWORK', 'MYK LATICRETE 315 PLUS GREY [20KG]', 'nos'),
  ('LA-CIVILWORK', 'ROFF 3 MM TILE SPACERS', 'Pcs'),
  ('LA-CIVILWORK', 'ULTRATECH CEMENT PPC GST 18%', 'bag'),
  ('LA-CIVILWORK', '8 MM VIZAG TMT', 'kg'),
  ('LA-CIVILWORK', 'GRANITE SLABS', 'sq.mtrs'),
  ('LA-CIVILWORK', 'LIME STONE', 'pcs'),
  ('LA-CIVILWORK', 'Polished Granites-Slabs', 'sft'),
  ('LA-PLUMBING WORK', '1" PVC BENDS', 'nos'),
  ('LA-PLUMBING WORK', 'PVC TAPE NO', 'nos'),
  ('LA-PLUMBING WORK', 'PVC NAIL CLAMPS 25MM-DOUBLE NAIL', 'pkt'),
  ('LA-ELECTRICAL', '2.5X3C COPPER FLATCABLE POLYCAB', 'mts'),
  ('LA-ELECTRICAL', '1.5MM CABLE-90 MTR RED-1,BLACK-2,YELLOW-1', 'coils'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Shera Plank Ammosia Afrmosia Brown 8mm', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Philips Screw Ebco Cbss 4025 SS Screw', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Star Bit', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cpvc Pipes Sdr 11 1"', 'nos'),
  ('LA-PLUMBING WORK', 'Astral Cpvc Tee 1"', 'nos'),
  ('LA-PLUMBING WORK', '1" Cpycv End Cap', 'nos'),
  ('LA-PLUMBING WORK', 'CPVC Reducer Tee 11/4"x1"', 'nos'),
  ('LA-PLUMBING WORK', 'Prince CPVC Solvent 237ML', 'nos'),
  ('LA-CIVILWORK', 'SANDY RED', 'box'),
  ('LA-CIVILWORK', 'SANDY GREY', 'box'),
  ('LA-PLUMBING WORK', '1" PVC PIPE NO PRECISSION - HMS', 'nos'),
  ('LA-ELECTRICAL', '2.5X3C COPPER FLEXIBLE WIRES POLYCAB', 'mtrs'),
  ('LA-CIVILWORK', 'NITOBOND SBR LATEX [20L]', 'btl'),
  ('LA-PLUMBING WORK', '1" PVC PIPE NOS PRECISSION-HMS -GREY', 'nos'),
  ('LA-PLUMBING WORK', '500MM CABLE TIE', 'pkt'),
  ('LA-PLUMBING WORK', 'PVC TAPE NOS', 'nos'),
  ('LA-PLUMBING WORK', 'PVC NAIL CLIP PKT 1" DOUBLE', 'pkt'),
  ('LA-ELECTRICAL', '22812-RECESSED POOL UNDER WATER -12W LED', 'nos'),
  ('LA-ELECTRICAL', '68357-12V SERIES IP67 POWER SUPPLY-15W', 'nos'),
  ('LA-ELECTRICAL', '27945-5M-24V-2835-6W/M FLEXIBLE LED STRIP-IP20', 'nos'),
  ('LA-ELECTRICAL', '68355-100W-4.2 24V SERIES POWER SUPPLY-IP67', 'nos'),
  ('LA-CIVILWORK', 'Sika Top 107 Seal Plus (A:B-2:5) -7kg', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'SS ANGELS 304', 'RFT'),
  ('LA-CIVILWORK', 'LATICRETE SP 100', 'nos'),
  ('LA-CIVILWORK', 'LATICRETE SP 100 STATIGREY', 'nos'),
  ('LA-CIVILWORK', 'LATICRETE SP 100 PLATINUM', 'nos'),
  ('LA-CIVILWORK', '4MM SPACER', 'nos'),
  ('LA-CIVILWORK', 'GROUT RUBBER WATER', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'TRIOSCOPE BRACKET 26988', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'TRIOSCOPE BRACKET 27057', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'RADIO MINI 6W LED BKT', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Angle Dixon', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', '24131-UNDERWATER LUMINAIRE', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', '68357-12 V SERIES POWER SUPPLY', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Shera plank', 'nos'),
  ('LA-PLUMBING WORK', '1" pvc pipes', 'nos'),
  ('LA-ELECTRICAL', '8WAY TPN DB BOARD LEGRAND', 'nos'),
  ('LA-ELECTRICAL', '40A 4P MCB', 'nos'),
  ('LA-ELECTRICAL', '40A 2P RCCB', 'nos'),
  ('LA-ELECTRICAL', '10A SP MCB', 'nos'),
  ('LA-ELECTRICAL', '200MM CABLE TIES', 'nos'),
  ('LA-ELECTRICAL', 'PVC TAPE BOX', 'nos'),
  ('LA-ELECTRICAL', '2.5MM COPPER PIN LUGS', 'nos'),
  ('LA-ELECTRICAL', 'PG GLANDS', 'nos'),
  ('LA-CIVILWORK', 'Polished Granites-Slabs', 'SQ. FT'),
  ('LA-CIVILWORK', 'ULTRATECH CEMENT PPC GST 18%', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'DRAIN SOUCER', 'nos'),
  ('LA-ELECTRICAL', 'LED POLE LIGHT', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Non Woven Geo Textile-Sqm 2mtr x 200mtr', 'SQM'),
  ('LA-ELECTRICAL', '38MM SC GLANDS', 'nos'),
  ('LA-ELECTRICAL', 'A-Z FERRULES', 'nos'),
  ('LA-ELECTRICAL', '2.5MM FERRULES', 'nos'),
  ('LA-ELECTRICAL', 'STRIP CONNECTOR', 'nos'),
  ('LA-CIVILWORK', 'HOT GANACHE-N APEX EMULSION', 'nos'),
  ('LA-CIVILWORK', '315 GREY', 'nos'),
  ('LA-CIVILWORK', 'SILVER SHADOW', 'nos'),
  ('LA-CIVILWORK', 'FILLER PLATINUM', 'nos'),
  ('LA-CIVILWORK', 'TILE CLEANER', 'nos'),
  ('LA-CIVILWORK', 'MYK 315 GREY', 'Nos'),
  ('LA-CIVILWORK', '3.75 PLATINUM', 'Nos'),
  ('LA-CIVILWORK', 'Laticrete Resin 1.25kg', 'nos'),
  ('LA-CIVILWORK', 'GUM CEMENT', 'nos'),
  ('LA-CIVILWORK', 'GRANITE SLABS', 'SQ FT'),
  ('LA-CIVILWORK', 'SLATE STONE', 'nos'),
  ('LA-ELECTRICAL', 'rope light- strip light', 'mtrs'),
  ('LA-ELECTRICAL', 'adapter', 'nos'),
  ('LA-CIVILWORK', 'MYK LATICRETE 315', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Supply,& Fabrication of ms partition for shera plank', 'nos'),
  ('LA-CIVILWORK', 'white sc sheath ex 20 ltr', 'nos'),
  ('LA-CIVILWORK', 'white pebbletex 30 kg', 'nos'),
  ('LA-CIVILWORK', 'SLAB ELENA (Size  600X1200X10)', 'nos'),
  ('LA-PLUMBING WORK', 'ASTRAL CPVC Ballvalve 1"', 'nos'),
  ('LA-PLUMBING WORK', 'ASTRAL PVC COUPLER 200MM', 'nos'),
  ('LA-PLUMBING WORK', 'CPVC BALL VALVE 1 1/4"', 'nos'),
  ('LA-PLUMBING WORK', 'Threaded Rod', 'nos'),
  ('LA-ELECTRICAL', 'Spikes Ony', 'nos'),
  ('LA-CIVILWORK', 'Vitrified Tiles', 'box'),
  ('LA-PLUMBING WORK', '1" cpvc Ball Valve', 'nos'),
  ('LA-PLUMBING WORK', 'Hard Plastic Valve Box', 'nos'),
  ('LA-PLUMBING WORK', '2" Screen Filter for sprinkler system', 'nos'),
  ('LA-PLUMBING WORK', 'Inline Lateral Pipe 40cm Spacing', 'Mtrs'),
  ('LA-PLUMBING WORK', 'FRP Enclosure For Controller', 'nos'),
  ('LA-PLUMBING WORK', 'ARV Assembly', 'nos'),
  ('LA-PLUMBING WORK', '1" Solenoid valve-HUNTER', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'Automation Contoller-Timer water meter-Hunter', 'nos'),
  ('LA-ELECTRICAL', 'Wire DB connectors', 'nos'),
  ('LA-PLUMBING WORK', 'CPVC Fittings', 'Set'),
  ('LA-PLANTAION', 'Lagestromia Speciosa', 'nos'),
  ('LA-PLANTAION', 'Foxtail Plams', 'nos'),
  ('LA-PLANTAION', 'Royal Palms', 'nos'),
  ('LA-PLANTAION', 'Plumaria Alba', 'nos'),
  ('LA-PLANTAION', 'Pluamria Dwarf', 'nos'),
  ('LA-PLANTAION', 'Filicium', 'nos'),
  ('LA-PLANTAION', 'Golden Witichia Palm', 'nos'),
  ('LA-PLANTAION', 'Helmalia Petans', 'nos'),
  ('LA-PLANTAION', 'Murayya Exotica', 'nos'),
  ('LA-PLANTAION', 'Hymencalis', 'nos'),
  ('LA-PLANTAION', 'Syzigium Campanulatum', 'nos'),
  ('LA-PLANTAION', 'Schflera Verigata', 'nos'),
  ('LA-PLANTAION', 'Galfimia Nitida', 'nos'),
  ('LA-PLANTAION', 'Bird Of Paradise', 'nos'),
  ('LA-PLANTAION', 'IXORA MINI', 'nos'),
  ('LA-PLANTAION', 'Alphinia Zerumbet', 'nos'),
  ('LA-PLANTAION', 'Calathea Lutea', 'nos'),
  ('LA-PLANTAION', 'XANADU', 'nos'),
  ('LA-PLANTAION', 'Fern', 'nos'),
  ('LA-PLANTAION', 'Vernonia', 'nos'),
  ('LA-PLANTAION', 'Bougainvillea', 'nos'),
  ('LA-PLANTAION', 'Sellum', 'nos'),
  ('LA-LANDSCAPE ELEMENT ITEMS', 'SS 304 SHEET', 'KG'),
  ('LA-ELECTRICAL', '2.5 X 3C COPPER ARMD CABLE', 'mtrs'),
  ('LA-CIVILWORK', 'Polished Granites-Slabs', 'SQ FT');