-- 028_multi_tenant.sql
-- Multi-tenant licensing & module access for the BOQ Manager.
--
-- Adds:
--   * tenants               - one row per customer company (Cogneta, EFC, ...)
--   * tenant_users          - users within a tenant, with bcrypt password + module access
--   * site_activation_codes - single-use codes issued by Cogneta per paid site
--   * sites.tenant_id       - every site belongs to exactly one tenant
--
-- IMPORTANT - before running this in Supabase SQL Editor:
--   1. cd app
--   2. node scripts/hash-seed-passwords.js
--   3. Paste the two INSERT INTO tenant_users statements that the script prints
--      where indicated below. Without that step the seed users have placeholder
--      hashes and you will not be able to log in.

CREATE TABLE IF NOT EXISTS tenants (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_code TEXT UNIQUE NOT NULL,
  company_name TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tenant_users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  username TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  allowed_modules TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  UNIQUE (tenant_id, username)
);

CREATE INDEX IF NOT EXISTS tenant_users_tenant_id_idx ON tenant_users(tenant_id);

CREATE TABLE IF NOT EXISTS site_activation_codes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT UNIQUE NOT NULL,
  tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  issued_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  issued_by TEXT,
  used_at TIMESTAMP WITH TIME ZONE,
  used_by_site_id UUID REFERENCES sites(id) ON DELETE SET NULL,
  notes TEXT
);

CREATE INDEX IF NOT EXISTS site_activation_codes_tenant_idx ON site_activation_codes(tenant_id);

-- Permissive RLS to match the rest of the schema (see schema.sql lines 228-276).
-- This is demo-grade auth - flagged in the plan and accepted for the pilot.
ALTER TABLE tenants                ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_users           ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_activation_codes  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Open access" ON tenants;
DROP POLICY IF EXISTS "Open access" ON tenant_users;
DROP POLICY IF EXISTS "Open access" ON site_activation_codes;

CREATE POLICY "Open access" ON tenants               FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Open access" ON tenant_users          FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Open access" ON site_activation_codes FOR ALL USING (TRUE) WITH CHECK (TRUE);

-- Add tenant_id to sites (nullable temporarily, backfilled below, then enforced NOT NULL).
ALTER TABLE sites ADD COLUMN IF NOT EXISTS tenant_id UUID REFERENCES tenants(id);
CREATE INDEX IF NOT EXISTS sites_tenant_id_idx ON sites(tenant_id);

-- Seed the two starting tenants. Run a second time is safe - ON CONFLICT skips dupes.
INSERT INTO tenants (company_code, company_name) VALUES
  ('Cogneta', 'Cogneta Automation'),
  ('EFC',     'EFC')
ON CONFLICT (company_code) DO NOTHING;

-- If the migration was applied before this change, the row above is skipped by
-- ON CONFLICT - so explicitly correct the display name. Idempotent.
UPDATE tenants SET company_name = 'Cogneta Automation' WHERE company_code = 'Cogneta';

-- Seed users. Bcrypt hashes generated by scripts/hash-seed-passwords.js.
-- Cogneta / Cogneta  -> superuser, every module.
-- EFC / admin        -> admin, just Dashboard + Sites + Manage Users (so the admin can grow the team).
INSERT INTO tenant_users (tenant_id, username, password_hash, full_name, role, allowed_modules) VALUES
  ((SELECT id FROM tenants WHERE company_code = 'Cogneta'), 'Cogneta', '$2b$10$QO6Bo7kNMRi29x2IPuLlG.08CFR8hxXqU.QyIxqcwIs6azUiRBg42', 'Cogneta Superuser', 'superuser', ARRAY['dashboard','sites','boq','boq-progress','ra-billing','workstations','material-grn','inventory','expenses','expense-dashboard','supplier-invoices','checklists','reports','master-data','admin-users','admin-codes','admin-tenants']::TEXT[]),
  ((SELECT id FROM tenants WHERE company_code = 'EFC'), 'admin', '$2b$10$6qL/IDaPHBSJabCLRubVBOTplTwqtKrmSCeZA7y02/oBPYq2yztlq', 'EFC Admin', 'admin', ARRAY['dashboard','sites','admin-users']::TEXT[])
ON CONFLICT (tenant_id, username) DO NOTHING;

-- Backfill: every existing site belongs to Cogneta (we own all pre-existing data).
UPDATE sites
   SET tenant_id = (SELECT id FROM tenants WHERE company_code = 'Cogneta')
 WHERE tenant_id IS NULL;

ALTER TABLE sites ALTER COLUMN tenant_id SET NOT NULL;
